# 运行端口
server:
  port: 10010
spring:
  # 数据库连接配置
  datasource:
    url: jdbc:mysql://localhost:3306/user_points?serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
# Dubbo配置
dubbo:
  application:
    name: user-points-service
    logger: slf4j
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20882
  scan:
    base-packages: com.damon.user_points