spring:
  profiles:
    active: @profileActive@
  freemarker:
    template-loader-path: classpath:/webapp/templates/
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    cache: false
  resources:
    static-locations: classpath:/webapp/static/
