server:
  port: 10081
  servlet:
    context-path: /${artifactId}
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  tomcat:
    uri-encoding: UTF-8
# Dubbo配置
dubbo:
  application:
    name: ${artifactId}
    logger: slf4j
  registry:
    address: zookeeper://127.0.0.1:2181
  consumer:
    check: false
  reference: -1
  service: -1