spring:
  profiles:
    active: @profileActive@
  freemarker:
    template-loader-path: classpath:/webapp/templates/
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    cache: false
    suffix: .ftl
  resources:
    static-locations: classpath:/webapp/static/
  mvc:
    hiddenmethod:
      filter:
        enabled: true
