spring:   
   rmq: rocketmq
   rocketmq:
    name-serv: localhost:9876
    producer-group: rmq-group
dubbo:
  application:
    name: ${artifactId}
    logger: slf4j
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.cn.rmq.service.impl