spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/reliable-message?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-test-query: SELECT 1
  rmq:
    mq:
      rocketmq:
        name-serv: localhost:9876
        producer-group: test
dubbo:
  application:
    name: ${artifactId}
    logger: slf4j
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.cn.rmq.service.impl