spring:
  rmq: kafka    # rocketmq,kafka
  #   rocketmq:
  #    name-serv: localhost:9876
  #    producer-group: rmq-group
  kafka:
    bootstrap-servers: localhost:9092
dubbo:
  application:
    name: ${artifactId}
    logger: slf4j
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: com.damon.rmq.service.impl
  reference:
    retries: -1
  service:
    retries: -1