dataSources:
  ds0: !!com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/reliable-message?serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root
  ds1: !!com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/reliable-message1?serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root

shardingRule:  
  tables:
    t_message: 
      actualDataNodes: ds${0..1}.t_message${0..1}
      databaseStrategy:
        inline:
          shardingColumn: id
          algorithmExpression: ds${Math.abs(id.hashCode())%2}
      tableStrategy: 
        inline:
          shardingColumn: consumer_queue
          algorithmExpression: t_message${Math.abs(consumer_queue.hashCode())%2}
  defaultDataSourceName: ds0
props:
  sql.show: true